### ISSUE TITLE
Verifying package-depends before packaging by default?

### ISSUE THREAD

**Issue by onesuper** [bernd/fpm-cookery#136]
Hi @bernd 

I notice that fpm-cookery will verify dependencies before it "installs" everything to a temp dir and lets fpm do the packaging stuff, unless a `--no-deps` option is used.

This option works for me when I package .rpm/.deb on my Mac. But i think the behavior is a little counter-intuitive.

Why should fpm-cookery do this verification by default? Why not just leave the resolution of the dependencies  to the package manager on target system before the real installation starts?

Regards
Yichao

**Comment by bernd** [comment]
@onesuper This is done because you might need some of the dependencies for building the software. Dependency handling will be refactored soon to not install dependencies by default. See: https://github.com/bernd/fpm-cookery/pull/131

Also, fpm-cookery expects packages to be built on the target platform. Building RPMs or DEBs on a Mac might work for packages which do not have any native dependencies (i.e. Java software) but breaks once the software you build requires any.
